### ISSUE TITLE
Gem prob ?

### ISSUE THREAD

**Issue by antinertia** [ryanckulp/product_hunt_upvotes#2]
Hi, 

I have a issue when I try to launch it. It happens after the link in the terminal. 

<img width="1680" alt="screen shot 2017-02-13 at 12 30 44" src="https://cloud.githubusercontent.com/assets/22873694/22883269/b73f5e0e-f1ef-11e6-8816-d35627dc0233.png">

Thanks

**Comment by ryanckulp** [comment]
@JeddiMees hey there, thanks for posting. 

i'm not getting this error. granted, i just tried on a fresh machine (ran `$ hunting_season`, then the script). 

you could also try the web version:
https://product-hunt-upvotes.herokuapp.com/

lemme know.

**Comment by antinertia** [comment]
@ryanckulp "Internal Server Error" when I try with the web version :/

**Comment by ryanckulp** [comment]
@JeddiMees when does the error happen? works for me when i run it. do you have a dev token?

what kind of URL are you submitting? it should be the product itself, ie http://generator.persistiq.com. NOT a product hunt URL.

**Comment by antinertia** [comment]
Ahh that's why ! Great it works :) Thanks !
